# Generated by Django 2.2 on 2019-05-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100)),
                ('writter', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
